CREATE SCHEMA dataRegistro;

USE dataRegistro;

CREATE TABLE usuarios (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(250),
    mail VARCHAR(250) NOT NULL,
    contrasenia VARCHAR(250) NOT NULL,
    fechaNacimiento DATE NOT NULL,
    dni INT NOT NULL,
    fotoPerfil VARCHAR(250),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    deletedAt TIMESTAMP NULL);
    
CREATE TABLE comentarios (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT UNSIGNED NOT NULL, 
	idProducto INT UNSIGNED NOT NULL, 
    textoComentario VARCHAR(250),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    deletedAt TIMESTAMP NULL,
    FOREIGN KEY (idUsuario) REFERENCES usuarios(id),
	FOREIGN KEY (idProducto) REFERENCES productos(id));

CREATE TABLE productos (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT UNSIGNED NOT NULL, 
    fotoProducto VARCHAR(250),
    nombreProducto VARCHAR(250) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    deletedAt TIMESTAMP NULL,
	FOREIGN KEY (idUsuario) REFERENCES usuarios(id));
    
    
    

    
    
    
